name: "Genshin Impact Helper Global"

on:
  schedule:
    - cron: "30 19 * * *"  # Minute/Hour/Day/Month/Weekday (UTC)
  workflow_dispatch:

env:
  RUN_ENV: 'prod'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (EXPERIMENTAL branch)
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Random sleep
        if: github.event_name == 'schedule'
        run: sleep $(shuf -i 10-600 -n 1)

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run sign
        env:
          USER_AGENT: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0'
          OS_COOKIE: ${{ secrets.OS_COOKIE }}
          PUSH_CONFIG: ${{ secrets.PUSH_CONFIG }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          python3 ./notify.py
